version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: forum-postgres
    environment:
      POSTGRES_DB: forum_voz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forum-network

  # MongoDB Database
  mongodb:
    image: mongo:6-jammy
    container_name: forum-mongodb
    environment:
      MONGO_INITDB_DATABASE: forum_voz
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - forum-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: forum-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - forum-network

  # pgAdmin (PostgreSQL GUI)
  pgadmin:
    image: dpage/pgadmin4
    container_name: forum-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - forum-network

  # Mongo Express (MongoDB GUI)
  mongo-express:
    image: mongo-express
    container_name: forum-mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - forum-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  forum-network:
    driver: bridge
